pool:
  vmImage: 'ubuntu-16.04'

variables:
  BuildConfiguration: 'Release'

steps:
- bash: dotnet restore
  displayName: Restore Packages

- bash: dotnet test test/GitBrowse.Test/GitBrowse.Test.csproj
  displayName: Run tests

- bash: |
    dotnet build --configuration $BUILDCONFIGURATION
    dotnet pack --no-build -o $BUILD_ARTIFACTSTAGINGDIRECTORY
  displayName: Package tool

- task: PublishBuildArtifacts@1
